### ISSUE TITLE
storage_size vs bit_size

### ISSUE THREAD

**Issue by MarDiehl** [szaghi/PENF#14]
https://github.com/szaghi/PENF/blob/d471d5ac793dde6793cb5fa4ca01ba73978d60bd/src/lib/penf_global_parameters_variables.F90#L150

would `storage_size` (https://gcc.gnu.org/onlinedocs/gfortran/STORAGE_005fSIZE.html) be an alternative for `bit_size`? It also works for reals.

**Comment by szaghi** [comment]
@MarDiehl my dear, you are right  think, it now being standard 2008 should be enough mature.

I am currently out of office for my holidays, but as soon as possible I'll try to replace the older built-in. Thank you very much for the improvement suggestion.

Regards
