### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by ShatrovOA** [szaghi/PENF#17]
Dear @szaghi !

I use PENF in my own little project. I also use FLAP that is dependent on PENF. I use FoBiS to build project. Recently I decided to update submodules and found out that FLAP doesn't use modules from its dependent version of PENF. It uses modules from my submodule that has been recently updated. 

Main problem is that R16P is now surrounded by _R16P macro and FLAP can't see that parameter any more.

My questions are: Why did you decide to surround R16P with a macro? What is the correct way to build project? Adding  _R16P macro to the fobos file?

I am assuming that FLAP is not the only example. Most of your projects use PENF..
Thank you!

**Comment by szaghi** [comment]
@ShatrovOA i am very sorry for my delay, I had to re-introduce that pre-processing flag because I am using nvfortran that does not support R16P kind. Today I have updated BeFoR64, FACE, FoXy and VTKFortran, tomorrow I'll continue the update of my libraries starting from FLAP.

Cheers

**Comment by ShatrovOA** [comment]
Thank you, just noticed fresh commit. My issue is no longer relevant, I'm closing it.

**Comment by szaghi** [comment]
@ShatrovOA 

I have just uploaded a new commit: it fixes some issues with the re-introduced _R16P pre-processing flag.

Thank you for the feedback, cheers
