### ISSUE TITLE
Customize separator in string conversion procedures

### ISSUE THREAD

**Issue by victorsndvg** [szaghi/PENF#5]
Hi @szaghi ,

in my fork I've added `separator`, an extra argument, to `str_a_*` procedures to allow clients to customize how to separate different elements of an array while converting to a string. It's not a great enhancement but i think it will be useful.

For example, I need this because FLAP `set` procedure needs strings for setting default values. While PENF returns array strings as "1,2,3,..", FLAP needs them in this way "1 2 3 ...".

**Comment by szaghi** [comment]
@victorsndvg this is wonderful.

I am quite busy these days, but I you open (another) PR I will accept it immediately.

**Comment by victorsndvg** [comment]
Sorry, I don't know how to do a PR with another PR pending ...

Don't worry, no rush, take the time you need :)

**Comment by szaghi** [comment]
@victorsndvg 

There are any news about this?

**Comment by victorsndvg** [comment]
Dear @szaghi ,

maybe I'm wrong, but I have been reading the code of your repo and I think that this is already merged into. Sorry, but my memory is so weak... 

If you see the [stringify module in master branch](https://github.com/szaghi/PENF/blob/master/src/lib/penf_stringify.F90) and search the word separator, you can see where this optional dummy argument could be used.

If I'm right, I think that this issue can be closed.

**Comment by szaghi** [comment]
@victorsndvg 

you are right. Sorry for the mistake.

cheers
