### ISSUE TITLE
PENF not compile as third party library with ifort 17.0.0

### ISSUE THREAD

**Issue by giacrossi** [szaghi/PENF#7]
When I try to compile PENF as a dependency for WenOOF via a simple fobos file, I obtain the following error:
`Compiling src/third_party/PENF/src/lib/penf.F90 serially`
`src/third_party/PENF/src/lib/penf.F90(1392): error #6405: The same named entity from different` `modules and/or program units cannot be referenced.   [BIT_SIZE]`
`use penf_b_size,  only : bit_size, byte_size`
`-------------------------^`
`compilation aborted for src/third_party/PENF/src/lib/penf.F90 (code 1)`

The options from the fobos file are the following:
 `FoBiS.py build -mode shared-intel`
`Module 'pygooglechart' not found: Gcov graphs disabled`
`Builder options`
`Directories`
`Building directory: "shared"`
`Compiled-objects .o   directory: "shared/obj"`
`Compiled-objects .mod directory: "shared/mod"`
`Compiler options`
`Vendor: "intel"`
`Compiler command: "ifort"`
`Module directory switch: "-module"`
`Compiling flags: "-cpp -c -fpic -assume realloc_lhs -O2"`
`Linking flags: "-shared -O2"`
`Preprocessing flags: ""`
`Coverage: False`
`Profile: False`
`PreForM.py used: False`
`PreForM.py output directory: None`
`PreForM.py extensions processed: []`

Building src/lib/wenoof.f90

**Comment by szaghi** [comment]
Dear @giacombum 

I am not able to reproduce your error without the fobos file you are **actually** using. With the PENF fobos the intel v 17 seems to work...

``` shell
stefano@zaghi(05:32 PM Fri Sep 23) on master desk {intel-17.0.0-beta - Intel Compilers 2017.0.0 beta environment}
~/fortran/PENF 14 files, 152Kb
→ FoBiS.py build -mode shared-intel
Builder options
  Directories
    Building directory: "shared"
    Compiled-objects .o   directory: "shared/obj"
    Compiled-objects .mod directory: "shared/mod"
  Compiler options
    Vendor: "intel"
    Compiler command: "ifort"
    Module directory switch: "-module"
    Compiling flags: "-cpp -c -fpic -assume realloc_lhs -O2"
    Linking flags: "-shared -O2"
    Preprocessing flags: ""
    Coverage: False
    Profile: False
  PreForM.py used: False
  PreForM.py output directory: None
  PreForM.py extensions processed: []

Building src/lib/penf.F90
Compiling src/lib/penf_global_parameters_variables.F90 serially
Compiling src/lib/penf_b_size.F90 serially
Compiling src/lib/penf_stringify.F90 serially
Compiling src/lib/penf.F90 serially
Linking shared/penf.so
Target src/lib/penf.F90 has been successfully built

stefano@zaghi(05:32 PM Fri Sep 23) on master [?] desk {intel-17.0.0-beta - Intel Compilers 2017.0.0 beta environment}
~/fortran/PENF 15 files, 156Kb
→ ifort --version
ifort (IFORT) 17.0.0 20160517
Copyright (C) 1985-2016 Intel Corporation.  All rights reserved
```
