### ISSUE TITLE
Wrong name in API documentation

### ISSUE THREAD

**Issue by cmacmackin** [szaghi/PENF#9]
Just noticed that in your FORD project file (and thus the docs on your Github pages) you are still referring to this library as IR_Precision. Thought I'd let you know.

**Comment by cmacmackin** [comment]
Sorry, it seems you just haven't updated the Github pages since your renaming. I see your project file is fine.

**Comment by szaghi** [comment]
@cmacmackin 

Thank you very much for pointing it out! It is time to update the API doc.

Cheers

**Comment by szaghi** [comment]
Fixed.
